/**
 * Homepage module — loads HTML templates from src/templates.js (generated at build time
 * from frontend/index.html and frontend/en.html), injects dynamic content at runtime.
 *
 * Templates are generated by scripts/build-config.cjs. Do not edit templates.js manually —
 * edit frontend/index.html and frontend/en.html instead.
 */

import { HTML_CN, HTML_EN } from './templates.js';

// ── Shared helpers ─────────────────────────────────────────────────

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
  });
}

function buildUpstreamList(names, basePath) {
  const entries = names.map((n) => '<span class="endpoint">' + basePath + '/' + n + '/dns-query</span>').join(' ');
  return entries || '<em>none</em>';
}

function inject(html, host, upstreams, names, configured, entrance) {
  const basePath = entrance || '';
  const htmlBasePath = escapeHtml(basePath);
  return html
    .replace('__BASE_PATH_JSON__', JSON.stringify(basePath))
    .replaceAll('__BASE_PATH__', htmlBasePath)
    .replaceAll('__HOST__', escapeHtml(host))
    .replace('__UPSTREAM_LIST__', buildUpstreamList(names, htmlBasePath))
    .replace('__EDNS_CAPS_TABLE__', buildCapsTable(upstreams))
    .replace('__CONFIGURED_VALUE__', String(configured || 0));
}

function buildCapsTable(upstreams) {
  if (!upstreams || Object.keys(upstreams).length === 0) return '<em>none</em>';
  let rows = '<table class="caps-table"><thead><tr><th>Upstream</th><th>ECS</th></tr></thead><tbody>';
  for (const [name, cfg] of Object.entries(upstreams)) {
    const ecs = cfg.ecs ? '<span class="yes">\u2705</span>' : '<span class="no">\u2716</span>';
    rows += `<tr><td><strong>${name}</strong></td><td>${ecs}</td></tr>`;
  }
  rows += '</tbody></table>';
  rows += '<p style="font-size:.78em;color:#888;margin-top:6px">ECS = EDNS Client-Subnet（地理位置优化 / geo-optimized resolution）</p>';
  return rows;
}

// ── Exports ────────────────────────────────────────────────────────

export function serveHomepage(request, upstreams, names, configured, entrance) {
  const host = new URL(request.url).host;
  return new Response(inject(HTML_CN, host, upstreams, names, configured, entrance), {
    status: 200,
    headers: { 'Content-Type': 'text/html;charset=utf-8' },
  });
}

export function serveHomepageEn(request, upstreams, names, configured, entrance) {
  const host = new URL(request.url).host;
  return new Response(inject(HTML_EN, host, upstreams, names, configured, entrance), {
    status: 200,
    headers: { 'Content-Type': 'text/html;charset=utf-8' },
  });
}